### ISSUE TITLE
Failed to load plugin 'redmine'

### ISSUE THREAD

**Issue by ruisantos78** [getsentry/sentry-redmine#16]
> I got a Successfully installed sentry-redmine-0.1.0 on my Sentry 9.0.0, but, beside the plugin not appear on integrations settings, I'm also receiving an error every time than I execute de command "sentry createruser":

> sentry createuser
Failed to load plugin 'redmine':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 31, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2320, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2343, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (redis 2.10.5 (/usr/local/lib/python2.7/site-packages), Requirement.parse('redis>=2.10.6'), set(['redis-py-cluster']))

> sentry plugins list
redmine: sentry-redmine 0.1.0 (/usr/local/lib/python2.7/site-packages)
jira: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
clubhouse: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
bitbucket: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
github: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
amazon_sqs: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
slack: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
pushover: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
gitlab: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
jira_ac: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
hipchat_ac: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
victorops: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
sessionstack: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
heroku: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
asana: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
pivotal: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
splunk: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
pagerduty: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
vsts: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)
segment: sentry-plugins 9.0.0 (/usr/local/lib/python2.7/site-packages)

>Installing collected packages: sentry-redmine
  Running setup.py install for sentry-redmine ... done
Successfully installed sentry-redmine-0.1.0

**Comment by saz** [comment]
Ran into the same issue.

redis-py-cluster depends on `redis>=2.10.6` since version 1.3.5, before it was depending on `redis>=2.10.2` (at least in 1.3.4).
Explicitly depending on 1.3.4 of redis-py-cluster will resolve the issue.

**Comment by qunabu** [comment]
this seems to be working 
```
docker-compose exec web pip install redis-py-cluster==1.3.4
docker-compose exec web pip install sentry-redmine
docker-compose restart web
```

**Comment by antoinm** [comment]
I had the same issue and after trying multiple workarounds, @qunabu 's one worked for me! Thanks!

**Comment by pavel-francirek** [comment]
Thank you, @qunabu  's workaround worked for me too. Would by nice in dependencies.
